#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.*
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
cp system/extrudeMeshDict1 system/extrudeMeshDict
extrudeMesh > extrudeMesh1.log
cp system/extrudeMeshDict2 system/extrudeMeshDict
extrudeMesh > extrudeMesh2.log
runApplication checkMesh

#------------------------------------------------------------------------------
