#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp 0/U.org 0/U
foamDictionary 0/U -entry "boundaryField.inlet"  -set "{ type fixedValue;  value uniform (8 0 0); }"
foamDictionary 0/U -entry "boundaryField.outlet"  -set "{ type zeroGradient; }"
rm -r log.potentialFoam
runApplication potentialFoam

foamDictionary 0/U \
  -entry "boundaryField.inlet" \
  -set "{ type variableHeightFlowRateInletVelocity; flowRate 25; alpha alpha.water; value uniform (0 0 0); }"
#foamDictionary 0/U \
# -entry "boundaryField.outlet" \
#  -set "{ type outletPhaseMeanVelocity; Umean  6; UnMean  6; alpha alpha.water; value uniform (6 0 0); }"
foamDictionary 0/U \
  -entry "boundaryField.outlet" \
  -set "{ type codedMixed; #include \"include/outletU\"; }"

rm log.setFields
runApplication setFields

#------------------------------------------------------------------------------
