#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cp $FOAM_TUTORIALS/resources/geometry/motorBike.obj.gz constant/triSurface/
# copy stl file onto constant/triSurface
# tar -xvzf mymodel.tar.gz

runApplication surfaceFeatures
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication extrudeMesh
runApplication checkMesh #this should output "Mesh OK."

# change the oldCase name
mapFields ../oldCase -sourceTime latestTime
foamDictionary system/controlDict -entry endTime -set 100
runApplication pimpleFoam &> pimpleFoam1.log

# runApplication decomposePar -copyZero
# runParallel snappyHexMesh -overwrite

# runParallel patchSummary
# runParallel potentialFoam
# runParallel $(getApplication)

mpirun -np 4 pimpleFoam -parallel >> pimpleFoam3.log 2>&1 || exit 1

# runApplication reconstructParMesh -constant
# runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
